Django_Lfit/Client/urls.py
from . import views
from .views import CustomView, login_client, logout_client
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^dashboard$', CustomView.as_view(template_name = 'Client/dashboard.html'), name="dashboard"),
    url(r'^training$', CustomView.as_view(template_name = 'Client/training.html'), name="training"),
    url(r'^competitions$', CustomView.as_view(template_name = 'Client/competition.html'), name="competitions"),
    url(r'^account$', CustomView.as_view(template_name = 'Client/account.html'), name="account"),   

#====#=====#====# Login URLs #====#=====#====#=====#

    url(r'^login$', login_client, name = "login"),
    url(r'^logout$', logout_client, name="logout"),

    url(r'^pie_plot$', views.pie_plot),
    
    #url(r'^home$', login_required(CustomView.as_view(template_name = 'Lfit/index.html'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Lfit/Django_Lfit/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from Lfit import views

urlpatterns = [
    url(r'^master$', views.login_redirect, name = 'login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('Lfit.urls', namespace="auth")),
    url(r'^user/', include('Client.urls', namespace="user")),
    # url(r'^profile/(?P<pk>[\d])$', views.edit_user, name="user_profile"),
]

Django_Lfit/Lfit/urls.py
from . import views
from .views import CustomView
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from django.contrib.auth.decorators import login_required
from Lfit.forms import CustomLoginForm as CLF


urlpatterns = [

    url(r'^home$', CustomView.as_view(template_name = 'Lfit/index.html'), name="home"),
    url(r'^clients$', CustomView.as_view(template_name = 'Lfit/clients.html'), name="clients"),
    url(r'^calendar$', CustomView.as_view(template_name = 'Lfit/calendar.html'), name="calendar"),
    url(r'^training$', CustomView.as_view(template_name = 'Lfit/training.html'), name="training"),
    url(r'^research$', views.research, name="research"), 
    # url(r'^research$', CustomView.as_view(template_name = 'Lfit/research.html')),
    url(r'^forms_nav$', CustomView.as_view(template_name = 'Lfit/forms_nav.html'), name="forms_nav"),    
    # url(r'^matty', views.mattyplot,name = 'matplotlib'),

    url(r'^personalinput$', views.personalinput, name = 'personalinput'),
    url(r'^compresultsinput$', views.compresultsinput, name = 'compresultsinput'),
    url(r'^paymentsinput$', views.paymentsinput, name = 'paymentsinput'),
    url(r'^cyclecreateinput$', views.cyclecreateinput, name = 'cyclecreatinput'),

    url(r'^research2$', views.line_graph),

#====#=====#====# Login URLs #====#=====#====#=====#

    url(r'^login$', login, {'template_name':'Lfit/login.html'}, name = "login"),
    url(r'^logout$', logout, {'template_name':'Lfit/logout.html'}, name="logout"),

    #url(r'^home$', login_required(CustomView.as_view(template_name = 'Lfit/index.html'))),

#====#=====#====# Advanced Form URLs #====#=====#====#=====#

    # url(r'^personalinput$', CustomFormView.as_view(template_name='Lfit/personalinput.html')),
    # url(r'^compresultsinput$', CustomFormView.as_view(template_name='Lfit/compresultsinput.html')),
    # url(r'^paymentsinput$', CustomFormView.as_view(template_name='Lfit/paymentsinput.html')),  
    # url(r'^cyclecreateinput$', CustomFormView.as_view(template_name='Lfit/cyclecreateinput.html')),  
]

Django_Lfit/Client/models.py
from django.db import models

# Create your models here.

Django_Lfit/Client/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

class CustomLoginForm(AuthenticationForm):
	class Meta: 
		model = User


class ImageUploadForm(forms.Form): 
	image = forms.ImageField()

Django_Lfit/Client/views.py
from django.shortcuts import render, redirect, reverse, render_to_response
from django.contrib.auth.decorators import login_required

from Lfit.models import PersonalInfo, CycleCreate


from calendar import HTMLCalendar

from django.views.generic import TemplateView
from django.views.generic.edit import FormView


from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User 

from Lfit.graphs import Graph

from Client.forms import ImageUploadForm


#@login_required
class CustomView(TemplateView):

	def get(self, request): 

		#TWO STEPS: Querying both models

		user_id = User.objects.filter(username=request.user)[0]
		user_profile = PersonalInfo.objects.filter(user=user_id)[0]

		if self.template_name == 'Client/dashboard.html':
				cycle_data = CycleCreate.objects.filter(client=user_profile)[0]
				Graph.plot_user(user_id, cycle_data.bpcttot, cycle_data.dpcttot, cycle_data.spctot)
				context = {'user':request.user, 'userprofile':user_profile, 'cycle_data':cycle_data}
				return render(request, self.template_name, context)

		if self.template_name == 'Client/training.html':
				context = {}
				return render(request, self.template_name, context) 

		if self.template_name == 'Client/account.html':
				context = {'user':request.user, 'userprofile':user_profile}
				return render(request, self.template_name, context)

		return render(request, self.template_name)

	def post(self,request): 

		if self.template_name == "Client/account.html":
			form = ImageUploadForm(request.POST,request.FILES)
			if form.is_valid():
				obj = PersonalInfo.objects.get(user=request.user)
				obj.profile_pic = form.cleaned_data['image']
				obj.save()

		return redirect("/user/account")


def pie_plot(request):
	return render(request, 'Lfit/pie/louie.html')


#===##===##===##===##===##===##===#
# Login VIEW
#===##===##===##===##===##===##===#
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .forms import CustomLoginForm
from django.template import RequestContext

def login_client(request):

	state = "Please login"

	if request.method == "POST" :
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			#===LOGIN CREDENTIALS were successful===#
			login(request, user)
			return redirect("/user/dashboard")

			#=====≠#  CUSTOM URL FOR UNIQUE USER #======#
			# return redirect("/%s/dashboard" % user)
		else:
			#===LOGIN CREDENTIALS have failed===#
			state = "Your name or password is not correct. Please try again"

	form = CustomLoginForm()
	return render(request,"Client/login.html", {"form":form,"state":state})

def logout_client(request):
	logout(request)
	return render(request, "Client/logout.html")

Django_Lfit/Django_Lfit/templates/Client/account.html
{% extends "clientbase.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block head%}
    <title>Lfit Account</title>
    <link rel="stylesheet" href="{% static 'dashboard.css' %}">
{% endblock head%}

{%block content%}
{% endblock content%}

{% block body %}
    <div class="container" style="padding-left:50px; padding-top:40px;">
        
        <h1>{{ userprofile }}</h1>    
        <br>
        <form action="{% url 'user:account' %}" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <p>Upload profile image here</p>
                {% csrf_token %}
                <input type="file" name="image">
            </div>
            <input type="submit" value="Upload" class="btn btn-primary">
        </form>
        
    </div>
{% endblock body%}

Django_Lfit/Django_Lfit/templates/Client/competition.html
{% extends "clientbase.html" %}
{% load staticfiles %}

{% block head%}
    <title>Competitions</title>
<!--    <link rel="stylesheet" href="{% static 'dashboard.css' %}">-->
{% endblock head%}


{% block body %}


    <script>
        document.getElementById("calendar_tabs").style.display = "block";
    </script>
{% endblock body%}

Django_Lfit/Django_Lfit/templates/Client/dashboard.html
{% extends "clientbase.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block head%}
    <title>Lfit dashboard</title>
    <script>
            $(function(){
                $("#includedContent").load("pie_plot");
            });
    </script>
    <link rel="stylesheet" href="{% static 'dashboard.css' %}">
{% endblock head%}


{% block body %}
    <div class="row no-pad">
    <div class="container col-lg-6">
        <p> USERNAME: {{ user.username }}</p>
        <p> CLIENT: {{ userprofile }}</p>
        <p> gender: {{ userprofile.gender }}</p>
        <p> {{cycle_data.client}} </p>        
        <br>
        <div style="width:100px">

        </div>
        <img src="{{ userprofile.profile_pic.url }}" width=240>
        </div>
        <div class="col-lg-6 pie_section">
        <div id="includedContent">
        </div>
        </div>
    </div>
    <script>
        console.log(document.getElementsByTagName("P"));
//        console.log(document.getElementsByClassName("container"));
    </script>
    <script>
        document.getElementById("dash_tabs").style.display = "block";
    </script>




{% endblock body%}

Django_Lfit/Django_Lfit/templates/Client/login.html
<!doctype html> 
{% load staticfiles %}
{% load bootstrap3 %}

<head>
    <title>Lfit</title>
    <link rel="stylesheet" href="{% static 'auth.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'cbstyles.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 
</head>

<body>
<div class="container-fixed customform">
	<br>
	<form action="{% url 'user:login' %}" class="form-signin" method="post" style="">
	   <h1 class="form-signin-header"> Lfit </h1>
            <br>
        <p style="text-align: center">{{state}}</p>
        <br>
		{% csrf_token %}
		{% bootstrap_form form layout='inline' %}
        {% buttons %}
        
		<button type="submit" class="btn btn-primary">{% bootstrap_icon "user" %} Login </button>
        
      {% endbuttons %}
	</form>
</div>
</body>

Django_Lfit/Django_Lfit/templates/Client/logout.html
<!doctype html> 
{% load staticfiles %}

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 
    <title>Logout</title>
    <link rel="stylesheet" href="{% static 'auth.css' %}">
</head>

<body>
    <div class="container customform">
        <h1> You're outta here! </h1>
        <br><br>
        <p> Successfully logged out from your account </p>
        <br><br>
        <p><a href="{% url 'user:login' %}">login</a></p>
    </div>
</body>

Django_Lfit/Django_Lfit/templates/Client/training.html
{% extends "clientbase.html" %}
{% load staticfiles %}

{% block head%}
    <title>User Training</title>
    <link rel="stylesheet" href="{% static 'dashboard.css' %}">
{% endblock head%}


{% block body %}

   <script>
        document.getElementById("training_tabs").style.display = "block";
    </script>
{% endblock body%}


 