Django_Lfit/Client/urls.py
from . import views
from .views import CustomView, login_client, logout_client
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^dashboard$', CustomView.as_view(template_name = 'Client/dashboard.html'), name="dashboard"),
    url(r'^training$', CustomView.as_view(template_name = 'Client/training.html'), name="training"),
    url(r'^competitions$', CustomView.as_view(template_name = 'Client/competition.html'), name="competitions"),
    url(r'^account$', CustomView.as_view(template_name = 'Client/account.html'), name="account"),   

#====#=====#====# Login URLs #====#=====#====#=====#

    url(r'^login$', login_client, name = "login"),
    url(r'^logout$', logout_client, name="logout"),

    url(r'^pie_plot$', views.pie_plot),
    
    #url(r'^home$', login_required(CustomView.as_view(template_name = 'Lfit/index.html'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Lfit/Django_Lfit/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from Lfit import views

urlpatterns = [
    url(r'^master$', views.login_redirect, name = 'login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('Lfit.urls', namespace="auth")),
    url(r'^user/', include('Client.urls', namespace="user")),
    # url(r'^profile/(?P<pk>[\d])$', views.edit_user, name="user_profile"),
]

Django_Lfit/Lfit/urls.py
from . import views
from .views import CustomView
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from django.contrib.auth.decorators import login_required
from Lfit.forms import CustomLoginForm as CLF


urlpatterns = [

    url(r'^home$', CustomView.as_view(template_name = 'Lfit/index.html'), name="home"),
    url(r'^clients$', CustomView.as_view(template_name = 'Lfit/clients.html'), name="clients"),
    url(r'^calendar$', CustomView.as_view(template_name = 'Lfit/calendar.html'), name="calendar"),
    url(r'^training$', CustomView.as_view(template_name = 'Lfit/training.html'), name="training"),
    url(r'^research$', views.research, name="research"), 
    # url(r'^research$', CustomView.as_view(template_name = 'Lfit/research.html')),
    url(r'^forms_nav$', CustomView.as_view(template_name = 'Lfit/forms_nav.html'), name="forms_nav"),    
    # url(r'^matty', views.mattyplot,name = 'matplotlib'),

    url(r'^personalinput$', views.personalinput, name = 'personalinput'),
    url(r'^compresultsinput$', views.compresultsinput, name = 'compresultsinput'),
    url(r'^paymentsinput$', views.paymentsinput, name = 'paymentsinput'),
    url(r'^cyclecreateinput$', views.cyclecreateinput, name = 'cyclecreatinput'),

    url(r'^research2$', views.line_graph),

#====#=====#====# Login URLs #====#=====#====#=====#

    url(r'^login$', login, {'template_name':'Lfit/login.html'}, name = "login"),
    url(r'^logout$', logout, {'template_name':'Lfit/logout.html'}, name="logout"),

    #url(r'^home$', login_required(CustomView.as_view(template_name = 'Lfit/index.html'))),

#====#=====#====# Advanced Form URLs #====#=====#====#=====#

    # url(r'^personalinput$', CustomFormView.as_view(template_name='Lfit/personalinput.html')),
    # url(r'^compresultsinput$', CustomFormView.as_view(template_name='Lfit/compresultsinput.html')),
    # url(r'^paymentsinput$', CustomFormView.as_view(template_name='Lfit/paymentsinput.html')),  
    # url(r'^cyclecreateinput$', CustomFormView.as_view(template_name='Lfit/cyclecreateinput.html')),  
]

Django_Lfit/Client/models.py
from django.db import models

# Create your models here.

Django_Lfit/Client/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

class CustomLoginForm(AuthenticationForm):
	class Meta: 
		model = User


class ImageUploadForm(forms.Form): 
	image = forms.ImageField()

Django_Lfit/Lfit/forms.py
from django import forms
from Lfit.models import PersonalInfo, CompResults, Payments, CycleCreate 
# from django.forms import CharField, DateField, IntegerField, ChoiceField, DecimalField

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

#===#===#===#===#===#===#
# Clients
#===#===#===#===#===#===#

class PersonalInfoForm(forms.ModelForm):
	class Meta:
		model = PersonalInfo
		fields = ['user','first', 'last', 'dob', 'age', 'gender', 
		'email', 'mobile', 'weightclass', 'agecategory',
		'affiliatedivision']

#===#===#===#===#===#===#
# Competition Results
#===#===#===#===#===#===#

class CompResultsForm(forms.ModelForm):
	class Meta:
		model = CompResults
		fields = ['client', 'compdate', 'compname', 
		'complocation', 'bodyweight', 'weightclass', 'sq1', 
		'sq2', 'sq3', 'bp1', 'bp2', 'bp3', 'dl1', 'dl2', 'dl3', 
		'comptotal', 'wilks']

#===#===#===#===#===#===#
# Payments Results
#===#===#===#===#===#===#

class PaymentsForm(forms.ModelForm):
	class Meta:
		model = Payments
		fields = ['paymentdate','client', 'cyclename',
		'payplan', 'weeks', 'totaltopay', 'paid', 'paymentmethod']

#===#===#===#===#===#===#
# Cycle Creation
#===#===#===#===#===#===#

class CycleCreateForm(forms.ModelForm):
	class Meta:
		model = CycleCreate
		fields = ['client', 'startdate', 'enddate',
		'trainingtype', 'days', 'weeks', 'sslots', 'bslots',
		'dslots', 'spctot', 'bpcttot', 'dpcttot', 'smpct', 
		'svpct', 'sspct', 'bmpct', 'bv1pct', 'bv2pct', 'bs1pct',
		'bs2pct', 'dmpct', 'dvpct', 'dspct', 'smApct', 
		'svApct', 'ssApct', 'bmApct', 'bv1Apct', 'bv2Apct',
		'bs1Apct', 'bs2Apct', 'dmApct', 'dvApct', 'dsApct', 
		'smmov', 'svmov', 'ssmov', 'bmmov', 'bv1mov', 'bv2mov',
		'bs1mov', 'bs2mov', 'dmmov', 'dvmov', 'dsmov', 'smAmov', 
		'svAmov', 'ssAmov', 'bmAmov', 'bv1Amov', 'bv2Amov',
		'bs1Amov', 'bs2Amov', 'dmAmov', 'dvAmov', 'dsAmov',]

class CustomLoginForm(AuthenticationForm):
	class Meta: 
		model = User

	def __init__(self, *args, **kwargs):
		super(MyForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs.update({'class' : 'myfieldclass'})
		self.fields['password'].widget.attrs.update({'class' : 'myfieldclass'})


#====#====##====#====##====#====##====#====#
# REGISTRATION FORM DEVELOPMENT
#====#====##====#====##====#====##====#====#

from django import forms 
from django.contrib.auth.models import User

class UserProfileForm(forms.ModelForm):
	class Meta: 
		model = User 
		fields = ['first_name', 'last_name', 'email']

Django_Lfit/Client/views.py
from django.shortcuts import render, redirect, reverse, render_to_response
from django.contrib.auth.decorators import login_required

from Lfit.models import PersonalInfo, CycleCreate


from calendar import HTMLCalendar

from django.views.generic import TemplateView
from django.views.generic.edit import FormView


from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User 

from Lfit.graphs import Graph

from Client.forms import ImageUploadForm


#@login_required
class CustomView(TemplateView):

	def get(self, request): 

		#TWO STEPS: Querying both models

		user_id = User.objects.filter(username=request.user)[0]
		user_profile = PersonalInfo.objects.filter(user=user_id)[0]

		if self.template_name == 'Client/dashboard.html':
				cycle_data = CycleCreate.objects.filter(client=user_profile)[0]
				Graph.plot_user(user_id, cycle_data.bpcttot, cycle_data.dpcttot, cycle_data.spctot)
				context = {'user':request.user, 'userprofile':user_profile, 'cycle_data':cycle_data}
				return render(request, self.template_name, context)

		if self.template_name == 'Client/training.html':
				context = {}
				return render(request, self.template_name, context) 

		if self.template_name == 'Client/account.html':
				context = {'user':request.user, 'userprofile':user_profile}
				return render(request, self.template_name, context)

		return render(request, self.template_name)

	def post(self,request): 

		if self.template_name == "Client/account.html":
			form = ImageUploadForm(request.POST,request.FILES)
			if form.is_valid():
				obj = PersonalInfo.objects.get(user=request.user)
				obj.profile_pic = form.cleaned_data['image']
				obj.save()

		return redirect("/user/account")


def pie_plot(request):
	return render(request, 'Lfit/pie/louie.html')


#===##===##===##===##===##===##===#
# Login VIEW
#===##===##===##===##===##===##===#
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .forms import CustomLoginForm
from django.template import RequestContext

def login_client(request):

	state = "Please login"

	if request.method == "POST" :
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			#===LOGIN CREDENTIALS were successful===#
			login(request, user)
			return redirect("/user/dashboard")

			#=====≠#  CUSTOM URL FOR UNIQUE USER #======#
			# return redirect("/%s/dashboard" % user)
		else:
			#===LOGIN CREDENTIALS have failed===#
			state = "Your name or password is not correct. Please try again"

	form = CustomLoginForm()
	return render(request,"Client/login.html", {"form":form,"state":state})

def logout_client(request):
	logout(request)
	return render(request, "Client/logout.html")

Django_Lfit/Lfit/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required

from Lfit.models import PersonalInfo, CompResults, Payments, CycleCreate
from .forms import PersonalInfoForm, CompResultsForm, PaymentsForm, CycleCreateForm  
from calendar import HTMLCalendar

from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from .graphs import Graph
import numpy as np
from mpld3 import fig_to_html
#from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas 

#@login_required
class CustomView(TemplateView):

	def get(self, request): 
		if self.template_name == 'Lfit/clients.html':
				query_personal = PersonalInfo.objects.all()
				query_comp = CompResults.objects.all()
				query_payments = Payments.objects.all()
				context = {'query_personal':query_personal, 'query_comp':query_comp, 'query_payments':query_payments, 'user':request.user}
				return render(request, self.template_name, context)

		if self.template_name == 'Lfit/training.html':
				query_live = CycleCreate.objects.filter(live='y')
				query_pending = CycleCreate.objects.filter(live='n')
				context = {'query_live':query_live, 'query_pending':query_pending}
				return render(request, self.template_name, context) 
		print('Template name: ', self.template_name)
		return render(request, self.template_name)

	def post(self, request):

		if self.template_name == 'Lfit/training.html':
			print("REQUEST: " , request.POST)
			print(request.POST['cycle'])
			cycle = CycleCreate.objects.get(cyclename = request.POST['cycle'])			
			print ('live: ' , cycle.live)
			if cycle.live == 'y':
				cycle.live = 'n'
			else:
				cycle.live = 'y'
			cycle.save()

			return redirect("/account/training")

def research(request): 
	#Graph.plotgraph()
	#canvas = FigureCanvas(fig)
	return render(request, 'Lfit/research.html')#, {'figure':figure})
	 
# Create your views here.

def line_graph(request):
	return render(request, 'Lfit/graph/S2B.html')


def login_redirect(request):
	return redirect('/account/login')

#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#
#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#
#
# DEVELOPMENT VIEWS
#
#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#
#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#===#


# === Personal Details Form ============================== #

def personalinput(request):
	if request.method == 'POST': 
		form = PersonalInfoForm(request.POST)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			return redirect('/account/home')
		else:
			return render(request, 'Lfit/personalinput.html', {'form': form})
	else: 
		form = PersonalInfoForm()
		return render(request, 'Lfit/personalinput.html', {'form': form})	

# === Competition Results Form =========================== #
def compresultsinput(request):
	if request.method == 'POST': 
		form = CompResultsForm(request.POST)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save
			return redirect('/account/home')
		else:
			return render(request, 'Lfit/compresultsinput.html', {'form': form})
	else: 
		form = CompResultsForm()
		return render(request, 'Lfit/compresultsinput.html', {'form': form})	

# === Payments Form ======================================= #
def paymentsinput(request):
	if request.method == 'POST': 
		form = PaymentsForm(request.POST)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			return redirect('/account/home')
		else:
			return render(request, 'Lfit/paymentsinput.html', {'form': form})
	else: 
		form = PaymentsForm()
		return render(request, 'Lfit/paymentsinput.html', {'form': form})	


# === Cycle Creation Form ================================= #
def cyclecreateinput(request):
	if request.method == 'POST': 
		form = CycleCreateForm(request.POST)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.cyclename = form.cleaned_data['trainingtype'] + str(form.cleaned_data['startdate']) + str(form.cleaned_data['enddate'])
			obj.save()
			return redirect('/account/home')
		else:
			return render(request, 'Lfit/cyclecreateinput.html', {'form': form})
	else: 
		form = CycleCreateForm()
		return render(request, 'Lfit/cyclecreateinput.html', {'form': form})	



# === Calendarrrrr???????? ================================= #

def calendarpage(request): 
	cal = HTMLCalendar()
	monthly = cal.formatmonth(2016,5)
	return render(request, 'Lfit/calendarproto.html', {'monthly': monthly})


#====Basic VIEWS (Original) ====# 

#@login_required 
# def index(request): 
# 	return render(request, 'Lfit/index.html')

# #@login_required 
# def clients(request): 
# 	if request.method == 'POST': 
# 		form = PersonalInfoForm(request.POST)
# 		if form.is_valid():
# 			return redirect(clients)
# 	return render(request, 'Lfit/clients.html')

# #@login_required 
# def calendar(request): 
# 	return render(request, 'Lfit/calendar.html')

# #@login_required 
# def training(request): 
# 	return render(request, 'Lfit/training.html')

# #@login_required 
# def research(request): 
# 	return render(request, 'Lfit/research.html')

# def forms_nav(request):
# 	return render(request, 'Lfit/forms_nav.html')

#====#=====#====# Advanced Custom Form View Function #====#=====#====#=====#


# class CustomFormView(FormView): 
# 	# template_name = 'Lfit/personalinput.html'
# 	form_class = PersonalInfoForm
# 	success_url = '/home'
# 	initial = {'key':'value'}

# 	def get(self, request, *args, **kwargs):
# 		form = self.form_class(initial=self.initial)
# 		print (self.get_form_class())
# 		return render(request, self.template_name, {'form': form})

# 	def form_valid(self, form): 
# 		obj = form.save(commit = False)
# 		obj.save()
# 		return redirect('/account/home')


#====#====##====#====##====#====##====#====#
# REGISTRATION FORM DEVELOPMENT
#====#====##====#====##====#====##====#====#

# from django.shortcuts import render, HttpResponseRedirect
# from django.contrib.auth.decorators import login_required
# from django.contrib.auth.models import User
# # from .models import UserProfile
# from Lfit.forms import UserProfileForm
# from django.forms.models import inlineformset_factory
# from django.core.exceptions import PermissionDenied

# @login_required
# def edit_user(request, pk):
#     user = User.objects.get(pk=pk)
#     user_form = UserProfileForm(instance=user)
 
#     ProfileInlineFormset = inlineformset_factory(User, UserProfile, fields=('phone', 'city', 'organization'))
#     formset = ProfileInlineFormset(instance=user)

#     if request.user.is_authenticated() and request.user.id == user.id:
#         print ("authenicated")
#         if request.method == "POST":
#             user_form = UserProfileForm(request.POST, request.FILES, instance=user)
#             formset = ProfileInlineFormset(request.POST, request.FILES, instance=user)
 
#             if user_form.is_valid():
#                 created_user = user_form.save(commit=False)
#                 formset = ProfileInlineFormset(request.POST, request.FILES, instance=created_user)
 
#                 if formset.is_valid():
#                     created_user.save()
#                     formset.save()
#                     return HttpResponseRedirect('/account/home')
 
#         return render(request, "Lfit/update_info.html", {
#             "noodle": pk,
#             "noodle_form": user_form,
#             "formset": formset,
#         })
#     else:
#         raise PermissionDenied

Django_Lfit/Django_Lfit/templates/Lfit/calendar.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head%}
    <title>Admin-Calendar</title>
{% endblock head%}

{% block body %}
<!--    CONTENT    -->        
    <div>
    </div>
    <div class="AtheletePage">
        <div>
          <h3>Calendar</h3>
          <p>This is where the Calendar content will be displayed</p>
        </div>
        <div class="container">
        
<!--        Contains the Calendar   -->                     <iframe src="https://calendar.google.com/calendar/embed?src=3gg73ss3180gloct31b0u6j38c%40group.calendar.google.com&ctz=Europe/London" style="border: 0" width="800" height="600" frameborder="0" scrolling="no">
        </iframe>            
            
        </div>
    </div>
    <script>
        document.getElementById("calendar_nav").style.backgroundColor = "#FFF";
        document.getElementById("calendar_nav").style.color = "#00d8ff";
            
    
    </script>
{% endblock body%}

Django_Lfit/Django_Lfit/templates/Lfit/calendar3.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head%}
    <title>Admin-Calendar</title>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.css' />
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.print.css' />
    <link rel='stylesheet' href='https://fullcalendar.io/css/base.css?3.1.0-1.5.0-4'/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type='text/javascript'  src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
    <script type='text/javascript'  src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.js'></script>

    <script>
            $(document).ready(function() {

                // page is now ready, initialize the calendar...

                $('#calendar').fullCalendar({
                    // put your options and callbacks here
                })

            });
    </script>

{% endblock head%}

{% block body %}
<!--    CONTENT    -->        
    <div class="AtheletePage">
        <div>
          <h3>Calendar</h3>
          <p>This is where the Calendar content will be displayed</p>
        </div>
        <div class="container">
        
<!--        Contains the Calendar   -->
            
            <div id='calendar'></div>            
        <iframe src="https://calendar.google.com/calendar/embed?src=3gg73ss3180gloct31b0u6j38c%40group.calendar.google.com&ctz=Europe/London" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>            
            
        </div>
    </div>
    <script>
        document.getElementById("calendar_nav").style.backgroundColor = "#000000"
        document.getElementById("calendar_nav").style.color = "white"
    </script>
{% endblock body%}

Django_Lfit/Django_Lfit/templates/Lfit/calendarproto.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head%}
    <title>Admin-Calendar</title>
    <link rel="stylesheet" href="{% static 'calendar.css' %}">
{% endblock head%}

{%block content%}
{% endblock content%}

{% block body %}
    
    {% load reading_tags %}

    <div id="calendar">
        {% reading_calendar year month reading_list %}
        <p> hello </p>
    </div>

    <!--JavaScript code-->
    <script> 
        document.getElementById("calendar").style.backgroundColor = "#000000"
        document.getElementById("calendar").style.color = "white"
    </script>
{% endblock body%}

Django_Lfit/Django_Lfit/templates/Lfit/clients.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head%}
    <title>Admin-Clients</title>
    <link rel="stylesheet" href="{% static 'clients.css' %}">
{% endblock head%}

{% block body %}
<!--    NAVBAR    -->

<!--    CONTENT    -->        
    <div class="AtheletePage">
        <div id="PersonalInfo" class="tabcontent" style="display:block">
          <h3>Personal Info.</h3>
          <p>This table displays personal information of all clients</p>
        <br><br>
        <div class="row no-pad">
            <div class="col-lg-10 col-lg-offset-1">
                <div class= "container-fixed table-responsive">
                <table class="table table-hover table-striped">
                <tr>
                    <th>First</th>
                    <th>Last</th>
                    <th>DOB</th>
                    <th>Age</th>
                    <th>Gender</th>
                    <th>Email</th>
                    <th>Mobile</th>
                    <th>Weight Class</th>
                    <th>Age category</th>
                    <th>Affiliate Division</th> 
                </tr>
                {% for n in query_personal %}
            <!--    <div class="pi-div">-->
                <tr>
                    <td>{{n.first}}</td>
                    <td>{{n.last}}</td>
                    <td>{{n.dob}}</td>
                    <td>{{n.age}}</td>
                    <td>{{n.gender}}</td>
                    <td>{{n.email}}</td>
                    <td>{{n.mobile}}</td>
                    <td>{{n.weightclass}}</td>
                    <td>{{n.agecategory}}</td>
                    <td>{{n.affiliatedivision}}</td>
                    <td id="option"><a href=#><i class="glyphicon glyphicon-edit"></i></a></td>
                </tr>
                {% endfor %}
                </table>
                </div>
            </div>
        </div>
        
        </div>

        <div id="Competition" class="tabcontent">
          <h3>Competition Results </h3>
          <p>This table shows all competition results</p> 
            <br><br>
            <div>
            <div class="container-fixed">
            <div class="row no-pad">
            <div class="col-lg-11 table-responsive">
                <table class="table table-hover table-striped">
                <tr>
                    <th>Comp. Date</th>
                    <th>Comp. Name</th>
                    <th>Location</th>
                    <th>Client</th>
                    <th>Gender</th>
                    <th>Age</th>
                    <th>Body Weight</th>
                    <th>Weight Class</th>
                    <th>SQ-1</th>
                    <th>SQ-2</th>
                    <th>SQ-3</th>
                    <th>BP-1</th>
                    <th>BP-2</th>
                    <th>Bp-3</th>
                    <th>DL-1</th>
                    <th>DL-2</th>
                    <th>DL-3</th>
                    <th>Total</th>
                    <th>Wilks</th>
                </tr>
                {% for n in query_comp %}
            <!--    <div class="pi-div">-->
                <tr>
                    <td>{{n.compdate}}</td>
                    <td>{{n.compname}}</td>
                    <td>{{n.complocation}}</td>
                    <td>{{n.client}}</td>
                    <td>{{n.gender}}</td>
                    <td>{{n.age}}</td>
                    <td>{{n.bodyweight}}</td>
                    <td>{{n.weightclass}}</td>
                    <td>{{n.sq1}}</td>
                    <td>{{n.sq2}}</td>
                    <td>{{n.sq3}}</td>
                    <td>{{n.bp1}}</td>
                    <td>{{n.bp2}}</td>
                    <td>{{n.bp3}}</td>
                    <td>{{n.dl1}}</td>
                    <td>{{n.dl2}}</td>
                    <td>{{n.dl3}}</td>
                    <td>{{n.comptotal}}</td>
                    <td>{{n.wilks}}</td>
                </tr>
                {% endfor %}
                </table>
            </div>
        </div>
        </div>
        </div>
        </div>
        

        <div id="Payments" class="tabcontent">
          <h3>Payments</h3>
          <p>This table shows current payments and plans</p>
            <br><br>
            <div class="container-fixed">
            <div class="row no-pad">
            <div class="col-lg-10 col-lg-offset-1 table-responsive">
                <table class="table table-hover table-striped">
                <tr>
                    <th>Pay Date</th>
                    <th>Client</th>
                    <th>Cycle</th>
                    <th>Pay Plan</th>
                    <th>Weeks</th>
                    <th>Total to Pay</th>
                    <th>Payment method</th>
                </tr>
                {% for n in query_payments %}
            <!--    <div class="pi-div">-->
                <tr>
                    <td>{{n.paymentdate}}</td>
                    <td>{{n.client}}</td>
                    <td>{{n.cyclename}}</td>
                    <td>{{n.payplan}}</td>
                    <td>{{n.weeks}}</td>
                    <td>{{n.totaltopay}}</td>
                    <td>{{n.paymentmethod}}</td>

                </tr>
                {% endfor %}
                </table>
        </div>
        
        </div>
            </div>
        </div>
    
    </div>

<!--    JavaScript    -->
    <script>
        function openCity(evt, cityName) {
        // Declare all variables
        var i, tabcontent, tablinks;

        // Get all elements with class="tabcontent" and hide them
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }

        // Get all elements with class="tablinks" and remove the class "active"
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }

        // Show the current tab, and add an "active" class to the link that opened the tab
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
        }    
    </script>
    <script>
        document.getElementById("clients").style.backgroundColor = "#FFF";
        document.getElementById("clients").style.color = "#00d8ff";
        
//        style="background-color:#000000; color:white"

    </script>

    <script>
        document.getElementById("client_tabs").style.display = "block";
    </script>

{% endblock body%}

Django_Lfit/Django_Lfit/templates/Lfit/login.html
<!doctype html> 
{% load staticfiles %}
{% load bootstrap3 %}

<head>
    <title>Lfit</title>
    <link rel="stylesheet" href="{% static 'auth.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'cbstyles.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 
</head>

<body>
<div class="container-fixed customform">
	<br>
	<form action="{% url 'auth:login' %}" class="form-signin" method="post">
	   <h1 class="form-signin-header"> Admin login </h1>
        <br>
		{% csrf_token %}
		{% bootstrap_form form layout='inline' %}
        {% buttons %}
        
		<button type="submit" class="btn btn-primary">{% bootstrap_icon "user" %} Login </button>
        {% endbuttons %}
	</form>
</div>
</body>