Django_Lfit/Client/urls.py
from . import views
from .views import CustomView, login_client, logout_client
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^dashboard$', CustomView.as_view(template_name = 'Client/dashboard.html'), name="dashboard"),
    url(r'^training$', CustomView.as_view(template_name = 'Client/training.html'), name="training"),
    url(r'^competitions$', CustomView.as_view(template_name = 'Client/competition.html'), name="competitions"),
    url(r'^account$', CustomView.as_view(template_name = 'Client/account.html'), name="account"),   

#====#=====#====# Login URLs #====#=====#====#=====#

    url(r'^login$', login_client, name = "login"),
    url(r'^logout$', logout_client, name="logout"),

    url(r'^pie_plot$', views.pie_plot),
    
    #url(r'^home$', login_required(CustomView.as_view(template_name = 'Lfit/index.html'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Lfit/Django_Lfit/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from Lfit import views

urlpatterns = [
    url(r'^master$', views.login_redirect, name = 'login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('Lfit.urls', namespace="auth")),
    url(r'^user/', include('Client.urls', namespace="user")),
    # url(r'^profile/(?P<pk>[\d])$', views.edit_user, name="user_profile"),
]

Django_Lfit/Lfit/urls.py
from . import views
from .views import CustomView
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from django.contrib.auth.decorators import login_required
from Lfit.forms import CustomLoginForm as CLF


urlpatterns = [

    url(r'^home$', CustomView.as_view(template_name = 'Lfit/index.html'), name="home"),
    url(r'^clients$', CustomView.as_view(template_name = 'Lfit/clients.html'), name="clients"),
    url(r'^calendar$', CustomView.as_view(template_name = 'Lfit/calendar.html'), name="calendar"),
    url(r'^training$', CustomView.as_view(template_name = 'Lfit/training.html'), name="training"),
    url(r'^research$', views.research, name="research"), 
    # url(r'^research$', CustomView.as_view(template_name = 'Lfit/research.html')),
    url(r'^forms_nav$', CustomView.as_view(template_name = 'Lfit/forms_nav.html'), name="forms_nav"),    
    # url(r'^matty', views.mattyplot,name = 'matplotlib'),

    url(r'^personalinput$', views.personalinput, name = 'personalinput'),
    url(r'^compresultsinput$', views.compresultsinput, name = 'compresultsinput'),
    url(r'^paymentsinput$', views.paymentsinput, name = 'paymentsinput'),
    url(r'^cyclecreateinput$', views.cyclecreateinput, name = 'cyclecreatinput'),

    url(r'^research2$', views.line_graph),

#====#=====#====# Login URLs #====#=====#====#=====#

    url(r'^login$', login, {'template_name':'Lfit/login.html'}, name = "login"),
    url(r'^logout$', logout, {'template_name':'Lfit/logout.html'}, name="logout"),

    #url(r'^home$', login_required(CustomView.as_view(template_name = 'Lfit/index.html'))),

#====#=====#====# Advanced Form URLs #====#=====#====#=====#

    # url(r'^personalinput$', CustomFormView.as_view(template_name='Lfit/personalinput.html')),
    # url(r'^compresultsinput$', CustomFormView.as_view(template_name='Lfit/compresultsinput.html')),
    # url(r'^paymentsinput$', CustomFormView.as_view(template_name='Lfit/paymentsinput.html')),  
    # url(r'^cyclecreateinput$', CustomFormView.as_view(template_name='Lfit/cyclecreateinput.html')),  
]

Django_Lfit/Django_Lfit/templates/base.html
<!doctype html> 
{% load staticfiles %}

<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="{% static 'base.css' %}">
        {% block head%}
            <title>NO TITLE</title>
        {% endblock head%}
    </head>
<!--    <body>-->
    <body style="background-color: #FFF;">


        <div class="row no-pad">
        <!-- sidebar*** -->
        <div class="col-lg-2 col-md-2 col-xs-2 side_column">
            <a href="{% url 'auth:home' %}"><img src="{% static 'img/Alpha_Logo.png' %}" class="brand-logo"></a>
            <div class="links" id="links">
                <div id="client_tabs" class="tablinks" style="display:none">
                    <p><a href="javascript:void(0)" onclick="openCity(event, 'PersonalInfo')" style="display:'active';">Personal Info</a></p>
                    <p><a href="javascript:void(0)" onclick="openCity(event, 'Competition')">Competition</a></p>
                    <p><a href="javascript:void(0)" onclick="openCity(event, 'Payments')">Payments</a></p>
                </div>
                <div id="training_tabs" class="tablinks" style="display:none">
                    <p><a href="javascript:void(0)" onclick="openCity(event, 'cycleCreation')" style="display:'active';">Cycle Creation</a></p>
                    <p><a href="javascript:void(0)" onclick="openCity(event, 'latestCycle')">Latest Creation</a></p>
                    <p><a href="javascript:void(0)" onclick="openCity(event, 'liveCycle')">Live Cycle</a></p>
                    <p><a href="javascript:void(0)" onclick="openCity(event, 'pendingCycle')">Pending Cycle</a></p>
                    <p><a href="javascript:void(0)" onclick="openCity(event, 'Analysis')">Analysis</a></p>
                </div>
                <div id="research_tabs" class="tablinks" style="display:none">
                    <p><a href="javascript:void(0)" onclick="openCity(event, 'PersonalInfo')" style="display:'active';">Fatigue v.s Strength</a></p>
                    <p><a href="javascript:void(0)" onclick="openCity(event, 'Competition')">Tab 2</a></p>
                    <p><a href="javascript:void(0)" onclick="openCity(event, 'Payments')">Tab 3</a></p>
                </div>            
            </div>
        </div>
        <!-- end/sidebar** -->


        <div class="col-lg-10 col-md-10 col-xs-10">
        <!-- main nav** -->
            <ul class="tab">
                <li class=""><a href="{% url 'auth:home' %}" id ='main'><i class="glyphicon glyphicon-home"> Main </i></a></li>
                <li class="tablinks"><a href="{% url 'auth:clients' %}" id='clients'> <i class="glyphicon glyphicon-user"> Clients </i></a></li>
                <li class="tablinks"><a href="{% url 'auth:training' %}" id='training'><i class="glyphicon glyphicon-book"> Training </i></a></li>
                <li class="tablinks"><a href="{% url 'auth:calendar' %}" id='calendar_nav'><i class="glyphicon glyphicon-calendar"> Calendar </i></a></li>
                <li class="tablinks"><a href="{% url 'auth:research' %}" id='research'><i class="glyphicon glyphicon-stats"> Research </i></a></li>
                <li class="tablinks"><a href="{% url 'auth:forms_nav' %}" id='forms_nav'>Forms</a></li>
                
                <li class="tablinks" style="float:right; margin-right:10px"><a href="{% url 'auth:logout' %}" id="logout" >Logout</a></li>
            </ul>
        <!-- end/main nav**    -->
        {% block body %}
        {% endblock body%}
        </div>
        </div>
    </body> 
</html>

Django_Lfit/Django_Lfit/templates/clientbase.html
<!doctype html> 
{% load staticfiles %}

<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="{% static 'clientbase.css' %}">
       <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        {% block head%}
            <title>NO TITLE</title>
        {% endblock head%}
    </head>

<body style="background-color: #FFF;">
        <div class="row">
        <!-- SIDE BAR -->
        <div class="col-lg-2 col-md-2 col-xs-2 side_column">
            <img src="{% static 'img/Alpha_Logo.png' %}" class="brand-logo">
            <div class="coachinfo">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-xs-6">
                        <img src="{% static 'img/coach.jpg' %}" class="brand-logo img-circle">
                    </div>
                    <div class="col-lg-6 col-md-6 col-xs-6">
                        <p> Coach </p>
                        <p> Couch Name </p>
                    </div>
                </div>
            </div>
            <br>
            <!-- side bar TABS -->
            <div id="dash_tabs" class="tablinks" style="display:none">
                <p><a href="javascript:void(0)" onclick="openCity(event, 'Overview')" style="display:'active';">Overview</a></p>
                <p><a href="javascript:void(0)" onclick="openCity(event, 'Todaytraining')" style="display:'active';">Today's training</a></p>
                <p><a href="javascript:void(0)" onclick="openCity(event, 'Coachanalysis')" style="display:'active';">Coach analysis</a></p>
            </div>
            <div id="training_tabs" class="tablinks" style="display:none">
                <p><a href="javascript:void(0)" onclick="openCity(event, 'Current')" style="display:'active';">Current</a></p>
                <p><a href="javascript:void(0)" onclick="openCity(event, 'Todayprotocol')" style="display:'active';">Today's Protocol</a></p>
                <p><a href="javascript:void(0)" onclick="openCity(event, 'Log')" style="display:'active';">Training Log</a></p>
                <p><a href="javascript:void(0)" onclick="openCity(event, 'Archive')" style="display:'active';">Cycle Archive</a></p>
            </div>
            <div id="calendar_tabs" class="tablinks" style="display:none">
                <p><a href="javascript:void(0)" onclick="openCity(event, 'Compoverview')" style="display:'active';">Competition Overview</a></p>
                <p><a href="javascript:void(0)" onclick="openCity(event, 'Compoverview')" style="display:'active';">History</a></p>
            <div id="account_tabs" class="tablinks" style="display:none">
            
                
            </div>   
            <!-- END/side bar TABS          -->
        </div>
            </div>
        <!-- END/sidebar -->

        <div class="col-lg-10 col-md-10 col-xs-10">
        <!-- MAIN NAV -->
            <nav class="navbar">
            <div class="container">
            <ul class="nav navbar-nav navbar-left">
                <li class="tablinks"><a href="{% url 'user:dashboard' %}" id ='dashboard'>Dashboard</a></li>
                <li class="tablinks"><a href="{% url 'user:training' %}" id='training'>Training</a></li>
                <li class="tablinks"><a href="{% url 'user:competitions' %}" id='competitions'>Competitions</a></li>
                <li class="tablinks"><a href="{% url 'user:account' %}" id='account'>Account</a></li>
<!--                <li class="tablinks" style="float:right; margin-right:10px"><a href="{% url 'user:logout' %}" id="logout" >Logout</a></li>-->  
            </ul>  
<!-- *Profile Dropdown* -->
            <ul class="nav navbar-right">
                <li class="dropdown" style="float:right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span>
                        <strong>{{cycle_data.client}}</strong>
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="navbar-login">
                                <div class="row">
                                    <div class="col-lg-4">
                                        <p class="text-center">
                                            <span class="glyphicon glyphicon-user icon-size"></span>
                                        </p>
                                    </div>
                                    <div class="col-lg-8">
                                        <p class="text-left"><strong>{{cycle_data.client}}</strong></p>
                                        <p class="text-left small">crazytodevelop@@gmail.com</p>
                                        <p class="text-left">
                                            <a href="#" class="btn btn-primary btn-block btn-sm">Profile</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="divider navbar-login-session-bg"></li>
                         <li><a href="#">Account Settings <span class="glyphicon glyphicon-cog pull-right"></span></a></li>
            <li class="divider"></li>
            <li><a href="#">User stats <span class="glyphicon glyphicon-stats pull-right"></span></a></li>
            <li class="divider"></li>
            <li><a href="#">Messages <span class="badge pull-right"> 42 </span></a></li>
            <li class="divider"></li>
            <li><a href="#">Favourites Snippets <span class="glyphicon glyphicon-heart pull-right"></span></a></li>
            <li class="divider"></li>
            <li><a href="{% url 'user:logout' %}">Sign Out <span class="glyphicon glyphicon-log-out pull-right"></span></a></li>
                    </ul>
                </li>
            </ul>
        <!-- END/main nav  -->

            </div>
            </nav>
            <section style="display:block">
        {% block body %}
            
        {% endblock body%}
            </section>
        </div>
        </div>
        <script>
        /* When the user clicks on the button, 
        toggle between hiding and showing the dropdown content */
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }

        // Close the dropdown if the user clicks outside of it
        window.onclick = function(e) {
          if (!e.target.matches('.dropbtn')) {

            var dropdowns = document.getElementsByClassName("dropdown-content");
            for (var d = 0; d < dropdowns.length; d++) {
              var openDropdown = dropdowns[d];
              if (openDropdown.classList.contains('show')) {
                openDropdown.classList.remove('show');
              }
            }
          }
        }
    </script>
    </body> 
</html>